### ISSUE TITLE
Generate and Install a profile to a git repository

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/pctl#14] opened 2021-04-13 11:30 UTC
This story is the `pctl` side of https://github.com/weaveworks/profiles/issues/27. Leaving here for tracking in this repo.

**Comment by cPu1** [comment] 2021-04-15 12:22
Duplicate of https://github.com/weaveworks/profiles/issues/27

**Closed** 2021-05-18 12:46 UTC
Labels: kind/feature
